{% set name = "lzip" %}
{% set version = "1.23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://download.savannah.gnu.org/releases/lzip/lzip-{{ version }}.tar.gz
  sha256: 4792c047ddf15ef29d55ba8e68a1a21e0cb7692d87ecdf7204419864582f280d

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
  host:
  run:

test:
  commands:
    - lzip --version

about:
  home: http://www.nongnu.org/lzip
  license: GPL
  license_family: GPL
  license_file: COPYING
  summary: Lzip is a lossless data compressor with a user interface similar to the one of gzip or bzip2.

  description: |
    Lzip is a lossless data compressor with a user interface similar to the
    one of gzip or bzip2. Lzip can compress about as fast as gzip (lzip -0),
    or compress most files more than bzip2 (lzip -9). Decompression speed is
    intermediate between gzip and bzip2. Lzip is better than gzip and bzip2
    from a data recovery perspective.

  dev_url: http://savannah.nongnu.org/projects/lzip

extra:
  recipe-maintainers:
    - sodre
